on: push
name: deploy
jobs:
  deploy:
    name: implementar en clúster
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: construir y empujar a docker
      uses: docker/build-push-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        repository: ${{ github.repository }}
        tag_with_ref: true
        tag_with_sha: true
        tahs: ${{ github.sha }}
